
#数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zsy_armor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx


jwt:
  issuer: Akuma
  secret: a8eac6910ede47b9bedf62127b837e56
  exp: 360



