
#数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.19.63.195:3306/armor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: armor
      password: v6x4nFmJbuA8dC26
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

redis:
  primary:
    database: 10
    host: 10.19.165.180
    port: 6379

jwt:
  issuer: zhixinhuixue.com
  secret: 593aa655d2014f5bba6a2e22d485eb12
  exp: 360

#FASTDFS服务
fastdfs:
  connectTimeout: 60
  networkTimeout : 120
  charset : UTF-8
  trackerHttpPort : 80
  antiStealToken : false
  trackerServer : 10.19.103.150:22122
  domain: http://fs.zhixinhuixue.com


#错误日志通知
logRedis:
  host: 10.19.165.180
  port: 6379
  database: 9
  key: zsy-system-err
  module: zsy-armor

#http basic验证
basic:
  user: zhixinhuixue.com
  password: iWK77vd6mULRsCZCMbFGIXmPN1w5Ueuw

#Qinu Oss服务
oss:
  bucketName: zsy-file-oss
  accessKey: PxMjAKZ-yOu94twi5VKGUbCMHwL1mYLOHdnXzr4p
  secretKey: m5GFGc0VeiX0Hcfoj35LLfpnEZcyP-eEhZjZ-fvg
  domain: report.zhixinhuixue.net