
server:
  context-path: /armor
  port: 10012


spring:
  profiles:
    active: dev #测试环境
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh

#Mybatis配置
mybatis:
  type-aliases-package: com.zhixinhuixue.armor.model
  mapper-locations:
    - classpath*:com/zhixinhuixue/armor/dao/**/*.xml

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
