
server:
  context-path: /armor
  port: 10012


spring:
  profiles:
    active: test #测试环境

#Mybatis配置
mybatis:
  type-aliases-package: com.zhixinhuixue.armor.model
  mapper-locations:
    - classpath*:com/zhixinhuixue/armor/dao/**/*.xml

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
