
#数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.251:3307/zsy_armor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: printer
      password: HnTqLszULNvNRR5b
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx


jwt:
  issuer: zhixinhuixue.com
  secret: 593aa655d2014f5bba6a2e22d485eb12
  exp: 360
