
#数据源
spring:
  redis:
    database: 10
    host: 192.168.1.240
    port: 6379
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.251:3307/zsy_armor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: printer
      password: HnTqLszULNvNRR5b
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx


jwt:
  issuer: zhixinhuixue.com
  secret: 593aa655d2014f5bba6a2e22d485eb12
  exp: 360

#FASTDFS服务
fastdfs:
  connectTimeout: 60
  networkTimeout : 120
  charset : UTF-8
  trackerHttpPort : 80
  antiStealToken : false
  trackerServer : 10.19.103.150:22122
  domain: http://fs.zhixinhuixue.com

