
#数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.210:3307/armor_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: zsy
      password: lc12345
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

  second-datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.251:3307/mantisbt?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: printer
      password: HnTqLszULNvNRR5b
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

redis:
  primary:
    database: 10
    host: 192.168.1.240
    port: 6379

#http basic验证
basic:
  user: xueping.com
  password: kaT9ewE91itIL9FBjGgcy9RMO0rL5F0F

jwt:
  issuer: Akuma
  secret: a8eac6910ede47b9bedf62127b837e56
  exp: 360

logging:
  level:
    com.zhixinhuixue.armor: debug

#FASTDFS服务
fastdfs:
  connectTimeout: 60
  networkTimeout : 120
  charset : UTF-8
  trackerHttpPort : 80
  antiStealToken : false
  trackerServer : 192.168.1.252:22122
  domain: http://fdfs.dev.xueping.com


#错误日志通知
logRedis:
  host: 192.168.1.240
  port: 6379
  database: 10
  key: zsy-system-err
  module: zsy-armor

#Qinu Oss服务
oss:
  bucketName: zsy-file-oss
  accessKey: PxMjAKZ-yOu94twi5VKGUbCMHwL1mYLOHdnXzr4p
  secretKey: m5GFGc0VeiX0Hcfoj35LLfpnEZcyP-eEhZjZ-fvg
  domain: report.zhixinhuixue.net

#密钥配置
ufile:
  publicKey: ucloudyunkaopei@outlook.com13615403931104805307
  privateKey: bcfd5bb66ca527c9be9fd7f3e784fbfc90c4bba5
  uploadProxySuffix: .cn-bj.ufileos.com
  bucketName: zxhx-test

#短信配置
sms:
  api: nothing
  appId: 6wax3awc7rfh5ijm
  appSecret: 3b47ba17f2eb45709312fce39fcc2d71
  smsTemplateOne: SMS_152507421
  smsTemplateTwo: SMS_152512354
  smsTemplateThree: SMS_152507424


