server:
  port: 10014

#数据源
spring:
  redis:
    database: 10
    host: 192.168.1.240
    port: 6379
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.251:3307/zsy_armor_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: printer
      password: HnTqLszULNvNRR5b
      filters: stat
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.jgeg,*.png,*.css,*.ico,/druid/*,*.eot,*.svg,*.ttf,*.woff,*.woff2'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: zxhx
        login-password: zxhx


jwt:
  issuer: xueping.com
  secret: 86a1e6b06a8e4ee29285158943931e9d
  exp: 360